stages:
    - release
    - build

variables:
    VLC_VERSION: "4.0"
    VLC_PATH: /Users/videolanci/sandbox/bin

############
## Builds ##
############

.continous-job-base-main:
    tags:
        - macos-xcode15
    stage: build
    only:
        - merge_requests
    interruptible: true

.continous-build-base-main:
    script:
        - ./compileAndBuildVLCKit.sh -${BUILD_PARAM}

continous-VLCKit-iOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vf"
        JOB_NAME: "MobileVLCKit"

continous-VLCKit-tvOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vft"
        JOB_NAME: "TVVLCKit"

continous-VLCKit-macOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vx"
        JOB_NAME: "VLCKit"

continous-VLCKit-xrOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vfi"
        JOB_NAME: "VLCKit-watchOS"

continous-VLCKit-watchOS-main:
    extends:
        - .continous-job-base-main
        - .continous-build-base-main
    variables:
        BUILD_PARAM: "vfw"
        JOB_NAME: "VLCKit-watchOS"

############################################################
## Development artifacts builds                           ##
## These are running every time a merge request is merged ##
## or a commit gets pushed to the default branch          ##
############################################################

.dev-artifacts-job-base-main:
    tags:
        - macos-xcode15
    rules:
        - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_PATH == "videolan/VLCKit"'
        - if: '$CI_COMMIT_TAG'
          when: never

    artifacts:
        paths:
            - ./*.tar.xz
    stage: build

.dev-artifacts-build-base-main:
    script:
        - ./compileAndBuildVLCKit.sh -${BUILD_PARAM}
        - ./Packaging/create-distributable-package.sh -${PACKAGING_PARAM}
        - mv *.tar.xz ${JOB_NAME}-${VLC_VERSION}-`date +%Y%m%d-%H%M`.tar.xz

dev-artifacts-VLCKit-iOS-main:
    extends:
        - .dev-artifacts-job-base-main
        - .dev-artifacts-build-base-main
    variables:
        BUILD_PARAM: "f"
        PACKAGING_PARAM: "m"
        JOB_NAME: "VLCKit-iOS"

dev-artifacts-VLCKit-tvOS-main:
    extends:
        - .dev-artifacts-job-base-main
        - .dev-artifacts-build-base-main
    variables:
        BUILD_PARAM: "ft"
        PACKAGING_PARAM: "t"
        JOB_NAME: "VLCKit-tvOS"

dev-artifacts-VLCKit-macOS-main:
    extends:
        - .dev-artifacts-job-base-main
        - .dev-artifacts-build-base-main
    variables:
        BUILD_PARAM: "x"
        PACKAGING_PARAM: "x"
        JOB_NAME: "VLCKit-macOS"

dev-artifacts-VLCKit-xrOS-main:
    extends:
        - .dev-artifacts-job-base-main
        - .dev-artifacts-build-base-main
    variables:
        BUILD_PARAM: "fi"
        PACKAGING_PARAM: "i"
        JOB_NAME: "VLCKit-xrOS"

dev-artifacts-VLCKit-watchOS-main:
    extends:
        - .dev-artifacts-job-base-main
        - .dev-artifacts-build-base-main
    variables:
        BUILD_PARAM: "fw"
        PACKAGING_PARAM: "w"
        JOB_NAME: "VLCKit-watchOS"

####################
## Release builds ##
####################

.release-job-base-main:
    tags:
        - macos-xcode15
    stage: release
    only:
        - tags
    artifacts:
        paths:
            - ./*.tar.xz

.release-build-base-main:
    script:
        - cd Packaging
        - ./buildAndDeployFrameworks.sh -${BUILD_PARAM}

MobileVLCKit-main:
    extends:
        - .release-job-base-main
        - .release-build-base-main
    variables:
        BUILD_PARAM: "m"

TVVLCKit-main:
    extends:
        - .release-job-base-main
        - .release-build-base-main
    variables:
        BUILD_PARAM: "t"

VLCKit-main:
    extends:
        - .release-job-base-main
        - .release-build-base-main
    variables:
        BUILD_PARAM: "x"
